{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.boltearth",
    "module": "bolt-earth-ui-sdk",
    "version": "9.9.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "devReleaseVariantDevReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.play",
          "module": "integrity",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.13.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.13.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.13.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.13.2"
          }
        },
        {
          "group": "in.juspay.merchants",
          "module": "hyper.assets.boltearth",
          "version": {
            "requires": "1.0.19"
          }
        },
        {
          "group": "in.juspay",
          "module": "hypersdk",
          "version": {
            "requires": "2.1.24"
          }
        },
        {
          "group": "in.juspay",
          "module": "hyperinteg",
          "version": {
            "requires": "2.1.24"
          }
        },
        {
          "group": "in.juspay",
          "module": "hyperlottie",
          "version": {
            "requires": "2.1.24"
          }
        },
        {
          "group": "in.juspay",
          "module": "hypernfc",
          "version": {
            "requires": "2.1.24"
          }
        }
      ],
      "files": [
        {
          "name": "bolt-earth-ui-sdk-9.9.9.aar",
          "url": "bolt-earth-ui-sdk-9.9.9.aar",
          "size": 10524825,
          "sha512": "c4edb35d0a7438dc72108d40a610b092231931516351fdeec1897ae5ccff3f3c35a0622e07f5e65f1e251cbff292af73ec6fcc3c0cf8fbf84ff693c2f474bd25",
          "sha256": "6bb9419bd9447756522f40d3fc1fc5fc404c40d0d6b328e31d9ff83540f3d608",
          "sha1": "cb7ff9caf55aae34a5367a75ba1777d7d15ca1e1",
          "md5": "f6c4743d9e48a5c8be9bc2fa970cdeaa"
        }
      ]
    },
    {
      "name": "devReleaseVariantDevReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.github.PhilJay",
          "module": "MPAndroidChart",
          "version": {
            "requires": "v3.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.54"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-bom",
          "version": {
            "requires": "4.10.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp"
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor"
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "no.nordicsemi.android.support.v18",
          "module": "scanner",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "no.nordicsemi.android",
          "module": "ble-common",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.gojek.courier",
          "module": "courier",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "com.gojek.courier",
          "module": "courier-message-adapter-gson",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "com.gojek.courier",
          "module": "courier-stream-adapter-rxjava2",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "com.gojek.courier",
          "module": "workmanager-pingsender",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.6.0"
          }
        },
        {
          "group": "com.google.android.flexbox",
          "module": "flexbox",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "de.hdodenhof",
          "module": "circleimageview",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.github.jakob-grabner",
          "module": "Circle-Progress-View",
          "version": {
            "requires": "v1.3"
          }
        },
        {
          "group": "com.github.razir.progressbutton",
          "module": "progressbutton",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "pl.droidsonroids.gif",
          "module": "android-gif-drawable",
          "version": {
            "requires": "1.2.31"
          }
        },
        {
          "group": "com.microsoft.clarity",
          "module": "clarity",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.hbb20",
          "module": "ccp",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.rudderstack.android.sdk",
          "module": "core",
          "version": {
            "requires": "1.25.1"
          }
        },
        {
          "group": "io.branch.sdk.android",
          "module": "library",
          "version": {
            "requires": "5.10.0"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "integrity",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.13.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.13.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.13.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.13.2"
          }
        },
        {
          "group": "in.juspay.merchants",
          "module": "hyper.assets.boltearth",
          "version": {
            "requires": "1.0.19"
          }
        },
        {
          "group": "in.juspay",
          "module": "hypersdk",
          "version": {
            "requires": "2.1.24"
          }
        },
        {
          "group": "in.juspay",
          "module": "hyperinteg",
          "version": {
            "requires": "2.1.24"
          }
        },
        {
          "group": "in.juspay",
          "module": "hyperlottie",
          "version": {
            "requires": "2.1.24"
          }
        },
        {
          "group": "in.juspay",
          "module": "hypernfc",
          "version": {
            "requires": "2.1.24"
          }
        }
      ],
      "files": [
        {
          "name": "bolt-earth-ui-sdk-9.9.9.aar",
          "url": "bolt-earth-ui-sdk-9.9.9.aar",
          "size": 10524825,
          "sha512": "c4edb35d0a7438dc72108d40a610b092231931516351fdeec1897ae5ccff3f3c35a0622e07f5e65f1e251cbff292af73ec6fcc3c0cf8fbf84ff693c2f474bd25",
          "sha256": "6bb9419bd9447756522f40d3fc1fc5fc404c40d0d6b328e31d9ff83540f3d608",
          "sha1": "cb7ff9caf55aae34a5367a75ba1777d7d15ca1e1",
          "md5": "f6c4743d9e48a5c8be9bc2fa970cdeaa"
        }
      ]
    }
  ]
}
